version: "3.8"

services:
    nginx:
        image: nginx:latest
        restart: always
        container_name: nginx
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8000:80"

    postgres-db:
        image: postgres:14.1-alpine
        restart: always
        container_name: postgres-db
        environment:
            - POSTGRES_USER=notification
            - POSTGRES_PASSWORD=notification
            - POSTGRES_DB=notifications
        ports:
            - "5432:5432"
        volumes:
            - ./psql-db:/var/lib/postgresql/data

    nosql-db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: nosql-db
        volumes:
            - ./mongo-db/:/data/db

    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
        container_name: redis
        volumes:
            - ./redis-db/:/redis/db

    customer:
        build:
            context: ./customer
            dockerfile: Dockerfile
        ports:
            - "8001:8001"
        container_name: customer
        restart: always

    products:
        build:
            context: ./products
            dockerfile: Dockerfile
        ports:
            - "8002:8002"
        container_name: products
        restart: always

    shopping:
        build:
            context: ./shopping
            dockerfile: Dockerfile
        ports:
            - "8003:8003"
        container_name: shopping
        restart: always

    payments:
        build:
            context: ./payments
            dockerfile: Dockerfile
        ports:
            - "8004:8004"
        container_name: payments
        restart: always

    mail:
        build:
            context: ./mail
            dockerfile: Dockerfile
        container_name: mail
        restart: always
